INSERT INTO USERS (USER_ID, EMAIL, PASSWORD, USERNAME)
    VALUES (999, 'maciekqwertyzaqwsx@gmail.com', '$2a$10$q5pIy.6HnZyj8bmk6gUr8umQodqsd1PUaJvg4IcEQa.BMRlyZV196', 'RICO5k');
INSERT INTO USER_ROLES (USER_ID, ROLES) VALUES (999, 'USER');

INSERT INTO USERS (USER_ID, EMAIL, PASSWORD, USERNAME)
    VALUES (998, 'alfa1@gmail.com', '$2a$10$TI/v1CU.RCswJoQJMbLD5usP6aSoNigYJWRS01RNxSGyDDIEKo/wm', 'alfa1');
INSERT INTO USER_ROLES (USER_ID, ROLES) VALUES (998, 'USER');


